### ISSUE TITLE
Баг при отрисовке окна

### ISSUE THREAD

**Issue by nzinoviev** [necromyhan/sdl_test#1]
При запуске на Ubuntu 23.04 с графическим сервером Wayland возникает баг при отрисовке окна.
![image](https://github.com/necromyhan/sdl_test/assets/72301688/dc8b4382-6e0c-4cbd-8f59-a1ed9af14bed)

При этом, если запустить приложение с правами админа, то окно отрисовывается корректно.
![CorrectRendering](https://github.com/necromyhan/sdl_test/assets/72301688/16c4b592-bc15-44f5-a085-3c7a7e0c5cd4)

**Comment by necromyhan** [comment]
Try to launch with "XDG_RUNTIME_DIR=".
